ca-cwds/cans-api

src/main/java/gov/ca/cwds/cans/Constants.java
src/main/java/gov/ca/cwds/cans/domain/dto/PersonDto.java
src/test/java/gov/ca/cwds/cans/rest/resource/PersonResourceTest.java

CANS-185. Post Person validation. Added alpha symbols validation for the first_name and last_name fields

---

jmeter/AssessmentsApi.jmx

Created a load test for PUT /assessments endpoint as the main application endpoint.
For 50 users simultaneously the application handles 107 PUT requests per seconds on local dev environment.

CANS-214. Create JMeter Tests for Load Testing

---

config/cans-api.yml

The application will run liquibase scripts on start up by default

Fix db upgrade on app start

---

Jenkinsfile
jenkinsfile-pull-request.groovy

Revert "Changed jenkins-slave"

---

src/test/java/gov/ca/cwds/cans/rest/resource/AbstractCrudFunctionalTest.java
src/test/java/gov/ca/cwds/cans/rest/resource/AssessmentResourceTest.java
src/test/java/gov/ca/cwds/cans/rest/resource/PersonResourceTest.java

Updated functional tests not to cleanup the created users and to allow to have other people in db

---

build.gradle

Update data model dependency version

Update data model dependency version

---

docker-tests/Readme.md

Updated Readme.md for tests docker image

Update Readme.md for tests docker image

---

.gitignore
build.gradle
src/main/java/gov/ca/cwds/cans/domain/dto/assessment/AbstractAssessmentDto.java
src/main/java/gov/ca/cwds/cans/domain/entity/Assessment.java
src/main/java/gov/ca/cwds/cans/domain/json/ItemJson.java
src/main/java/gov/ca/cwds/cans/service/AssessmentService.java
src/test/resources/fixtures/assessment-post.json
src/test/resources/fixtures/assessment-put.json
src/test/resources/fixtures/assessment-read.json
src/test/resources/fixtures/instrument-ca-post.json
src/test/resources/fixtures/instrument-post.json
tools/instrument-parser/js/structure-converter.js
tools/instrument-parser/js/template.js

Cans-173 confidential logic 

---

src/main/java/gov/ca/cwds/cans/domain/dto/PersonDto.java
src/test/java/gov/ca/cwds/cans/rest/resource/PersonResourceTest.java
src/test/resources/fixtures/person-post.json
src/test/resources/fixtures/person-put.json

CANS-239. Add Client # to Child's Profile. Validation

---

.gitignore
tools/instrument-parser/index.js
tools/instrument-parser/js/object-to-liquibase.js
tools/instrument-parser/js/template.js
tools/instrument-parser/js/util.js
tools/instrument-parser/readme.md

Improve instrument parser to generate Update changelogs instead of create

---

src/main/java/gov/ca/cwds/cans/domain/dto/PersonDto.java
src/test/java/gov/ca/cwds/cans/rest/resource/PersonResourceTest.java

CANS-239. Add Client # to Child's Profile. Validation for null/empty value

---

src/main/java/gov/ca/cwds/cans/CansConfiguration.java
src/main/java/gov/ca/cwds/cans/dao/AbstractCrudDao.java
src/main/java/gov/ca/cwds/cans/dao/hibernate/JsonType.java
src/main/java/gov/ca/cwds/cans/domain/dto/assessment/AssessmentDto.java
src/main/java/gov/ca/cwds/cans/domain/entity/Assessment.java
src/main/java/gov/ca/cwds/cans/service/AssessmentService.java
src/main/java/gov/ca/cwds/cans/service/InstrumentService.java
src/main/java/gov/ca/cwds/cans/service/PersonService.java
src/main/java/gov/ca/cwds/cans/util/DbUpgrader.java
src/main/java/gov/ca/cwds/cans/validation/ValidAssessment.java
src/main/java/gov/ca/cwds/cans/validation/ValidAssessmentValidator.java
src/test/java/gov/ca/cwds/cans/rest/resource/AssessmentResourceTest.java
src/test/resources/fixtures/assessment/assessment-post-logging-info.json
src/test/resources/fixtures/assessment/assessment-post-submit-fail.json
src/test/resources/fixtures/assessment/assessment-post.json
src/test/resources/fixtures/assessment/assessment-put.json
src/test/resources/fixtures/assessment/assessment-read.json
src/test/resources/fixtures/instrument-post.json

Added validation for assessment submission

CANS-209. Social Worker "submits" a CANS Assessment

---

jmeter/AssessmentsApi.jmx

FIX: Performance tests

---

src/main/java/gov/ca/cwds/cans/domain/dto/assessment/AssessmentDto.java
src/main/java/gov/ca/cwds/cans/domain/entity/Assessment.java
src/main/java/gov/ca/cwds/cans/domain/json/AssessmentJson.java
src/main/java/gov/ca/cwds/cans/domain/json/DomainJson.java
src/main/java/gov/ca/cwds/cans/service/AssessmentService.java
src/main/java/gov/ca/cwds/cans/validation/ValidAssessmentValidator.java
src/test/java/gov/ca/cwds/cans/rest/resource/AssessmentResourceTest.java
src/test/resources/fixtures/assessment/assessment-post-submit-fail.json
src/test/resources/fixtures/assessment/assessment-post.json

1. Added caregiver name field to DomainJson 
2. Added validation for the field to have a length shorter than 50 symbols
3. Moved Assessment validation to resource layer to fail fast for invalid assessment

CANS-253. Caregiver Domain collects Caregiver Name and displays it in header

---

README.md
build.gradle
src/main/java/gov/ca/cwds/cans/domain/dto/assessment/AbstractAssessmentDto.java
src/main/java/gov/ca/cwds/cans/domain/entity/Assessment.java
src/main/java/gov/ca/cwds/cans/service/AssessmentService.java
src/main/java/gov/ca/cwds/cans/validation/ValidAssessmentValidator.java
src/test/java/gov/ca/cwds/cans/rest/resource/AssessmentResourceTest.java
src/test/resources/fixtures/assessment/assessment-post.json
src/test/resources/fixtures/assessment/assessment-put.json
src/test/resources/fixtures/assessment/assessment-read.json

Add has_caregiver to Assessment
[CANS-179](https://osi-cwds.atlassian.net/browse/CANS-179)

Cans 179 has caregiver

---

build.gradle
src/main/java/gov/ca/cwds/cans/Constants.java
src/main/java/gov/ca/cwds/cans/domain/dto/PersonDto.java
src/main/java/gov/ca/cwds/cans/domain/entity/Person.java
src/test/java/gov/ca/cwds/cans/rest/resource/PersonResourceTest.java
src/test/resources/fixtures/person-get-all.json
src/test/resources/fixtures/person-post.json
src/test/resources/fixtures/person-put.json
src/test/resources/fixtures/person-search-clients-response.json

CANS-255 add middle name and suffix

---

src/test/java/gov/ca/cwds/cans/rest/resource/PersonResourceTest.java

- [x ] My code follows the code style of this project.
- [ x] I ran all my tests locally which were green.
- [x ] My code adds no new issues to Code Climate
- [ x] I ran all the linters and static analyzers for the project (SonarQube, eslint, rubocop, etc).
- [ x] My code is in a stable state ready to be deployable, but not necessarily complete.

cans-api-263 added caseId validation to snyc with master

---

src/test/java/gov/ca/cwds/cans/rest/resource/PersonResourceTest.java

Fix functional test

---

src/main/java/gov/ca/cwds/cans/Constants.java
src/main/java/gov/ca/cwds/cans/domain/dto/PersonDto.java
src/test/java/gov/ca/cwds/cans/rest/resource/PersonResourceTest.java

Cans-254 remove special character constraints from person name fields

---

build.gradle

Increment version

---

build.gradle

Update project version

---

jmeter/AssessmentsApi.jmx

Fix performance tests

---

Jenkinsfile

Change default var values for jenkins job

---

src/main/java/gov/ca/cwds/cans/rest/resource/SecurityResource.java
src/test/java/gov/ca/cwds/cans/rest/resource/AuthorizationResourceTest.java

SecurityResource security added to comply new security rules

CANS-291: SecurityResource security added to comply new security rules

---

src/main/java/gov/ca/cwds/cans/CansApplication.java
src/main/java/gov/ca/cwds/cans/security/PersonWriteAuthorizer.java
src/main/java/gov/ca/cwds/cans/service/PersonService.java
src/main/resources/authorization-rules/assessment-authorization-rules.drl
src/main/resources/authorization-rules/person-authorization-rules.drl
src/test/java/gov/ca/cwds/cans/rest/resource/AbstractCrudFunctionalTest.java
src/test/java/gov/ca/cwds/cans/rest/resource/AbstractFunctionalTest.java
src/test/java/gov/ca/cwds/cans/rest/resource/AssessmentResourceTest.java
src/test/java/gov/ca/cwds/cans/rest/resource/PersonResourceTest.java
src/test/java/gov/ca/cwds/cans/security/AssessmentReadAuthorizerTest.java
src/test/java/gov/ca/cwds/cans/security/PersonReadAuthorizerTest.java
src/test/resources/fixtures/perry-account/el-dorado-all-authorized.json
src/test/resources/fixtures/person-put.json

https://osi-cwds.atlassian.net/browse/CANS-337

CANS-337: county check rule

---

build.gradle
docker-compose.yml
src/main/java/gov/ca/cwds/cans/rest/resource/SystemInformationResource.java

Improvement of reusable AbstractSystemInformationResource
https://osi-cwds.atlassian.net/browse/CANS-432

CANS-432: Update cans-api to use system-information json format

---

build.gradle

Increment project version

---

build.gradle

CANS-631: Develop backend functionality for Case Worker Dashboard

---

build.gradle
src/main/java/gov/ca/cwds/cans/rest/resource/StaffResource.java
src/main/java/gov/ca/cwds/cans/service/StaffService.java
src/test/java/gov/ca/cwds/cans/rest/resource/StaffResourceTest.java

CANS-631: bug fix

---

src/main/java/gov/ca/cwds/cans/service/StaffService.java

Fix Duplicate key exception

---

src/main/java/gov/ca/cwds/cans/domain/entity/Person.java
src/test/java/gov/ca/cwds/cans/rest/resource/StaffResourceTest.java

CANS-631: most recent assessment query bug fix

---

build.gradle

Update api-core dependency version

Update api-core dependency version

---

src/main/java/gov/ca/cwds/cans/domain/mapper/ClientMapper.java

Fix null pointer in client mapping
Name suffix mapping

Fix null pointer in client mapping

---

src/main/java/gov/ca/cwds/cans/domain/entity/Person.java
src/main/java/gov/ca/cwds/cans/domain/mapper/StaffClientMapper.java
src/main/java/gov/ca/cwds/cans/service/StaffService.java
src/test/java/gov/ca/cwds/cans/rest/resource/StaffResourceTest.java

CANS-631: legacy client identifier usage

---

src/main/java/gov/ca/cwds/cans/domain/entity/Person.java
src/test/java/gov/ca/cwds/cans/rest/resource/StaffResourceTest.java

CANS-631: duplication bug fix

---

build.gradle
src/main/java/gov/ca/cwds/cans/domain/dto/assessment/AbstractAssessmentDto.java
src/main/java/gov/ca/cwds/cans/domain/entity/Assessment.java
src/main/java/gov/ca/cwds/cans/domain/entity/Person.java
src/main/java/gov/ca/cwds/cans/validation/PersistentAware.java
src/main/java/gov/ca/cwds/cans/validation/ValidAssessmentValidator.java
src/test/java/gov/ca/cwds/cans/InMemoryFunctionalTestSuite.java
src/test/java/gov/ca/cwds/cans/rest/resource/AssessmentResourceTest.java
src/test/resources/fixtures/assessment/assessment-post.json

Implementation of capturing Name of Person that Conducted the Assessment

CANS-325 Capture Name of Person that Conducted the Assessment

---

src/main/java/gov/ca/cwds/cans/rest/resource/StaffResource.java
src/main/java/gov/ca/cwds/cans/validation/ValidStaffId.java
src/main/java/gov/ca/cwds/cans/validation/ValidStaffIdValidator.java
src/test/java/gov/ca/cwds/cans/rest/resource/StaffResourceTest.java
src/test/java/gov/ca/cwds/cans/validation/ValidStaffIdValidatorTest.java

Add validation to staffId in StaffResource

Add validation for staffId in StaffResource

---

build.gradle
src/main/java/gov/ca/cwds/cans/service/ClientsService.java

https://osi-cwds.atlassian.net/browse/CANS-663
Update: Rework referral ids fetching

CANS-663. Referral/Case Number Refactored

---

src/main/java/gov/ca/cwds/cans/CansApplication.java
src/main/java/gov/ca/cwds/cans/rest/resource/StaffResource.java
src/main/java/gov/ca/cwds/cans/security/StaffPersonReadAuthorizer.java
src/main/java/gov/ca/cwds/cans/service/StaffService.java
src/test/java/gov/ca/cwds/cans/FunctionalTestSuite.java
src/test/java/gov/ca/cwds/cans/rest/resource/AssessmentResourceAuthorizationTest.java
src/test/java/gov/ca/cwds/cans/rest/resource/StaffResourceTest.java
src/test/java/gov/ca/cwds/cans/security/StaffPersonReadAuthorizerTest.java

https://osi-cwds.atlassian.net/browse/CANS-537

CANS-537. Authorize Supervisor to see subordinates' dashboards

---

src/main/java/gov/ca/cwds/cans/dao/AssessmentDao.java
src/main/java/gov/ca/cwds/cans/security/AssessmentReadAuthorizer.java
src/main/java/gov/ca/cwds/cans/security/AssessmentWriteAuthorizer.java
src/main/java/gov/ca/cwds/cans/security/ClientReadAuthorizer.java
src/main/java/gov/ca/cwds/cans/service/PersonService.java
src/main/java/gov/ca/cwds/cans/service/StaffService.java

Small clean up of SonarCube code smells

CANS-736: fix SonarCube code smells

---

build.gradle

The issue with query parameters for authorization call fixed

CANS-736: new version of API core

---

src/test/resources/fixtures/perry-account/000-all-authorized.json
src/test/resources/fixtures/perry-account/0ki-marlin-none.json
src/test/resources/fixtures/perry-account/0ki-napa-all.json
src/test/resources/fixtures/perry-account/1126-all-authorized.json
src/test/resources/fixtures/perry-account/account-napa-all.json
src/test/resources/fixtures/perry-account/account-napa-none.json
src/test/resources/fixtures/perry-account/authorized-no-sealed.json
src/test/resources/fixtures/perry-account/el-dorado-all-authorized.json
src/test/resources/fixtures/perry-account/el-dorado-sealed-authorized.json
src/test/resources/fixtures/perry-account/marin-all-authorized.json
src/test/resources/fixtures/perry-account/marlin-unauthorized.json
src/test/resources/fixtures/perry-account/no_sealed_no_sensitive-authorized.json
src/test/resources/fixtures/perry-account/not-authorized-with-cans-privilege.json
src/test/resources/fixtures/perry-account/not-authorized-with-cans-role.json
src/test/resources/fixtures/perry-account/sealed-authorized.json
src/test/resources/fixtures/perry-account/sensitive_persons-authorized.json
src/test/resources/fixtures/perry-account/single-county-authorized.json
src/test/resources/fixtures/perry-account/state-of-california-all-authorized.json
src/test/resources/fixtures/perry-account/state-of-california-no-sensitivity-no-sealed.json
src/test/resources/fixtures/perry-account/zzz-not-authorized.json

https://osi-cwds.atlassian.net/browse/CANS-644
Fixtures changes to fix integration tests

CANS-644: fixtures changes to fix integration tests

---

src/main/java/gov/ca/cwds/cans/service/ChangeLogService.java

fix order to use timestamp instead of revision number.

CANS-780 Provide the name of change agent to CANS API

---

src/main/java/gov/ca/cwds/cans/domain/mapper/AssessmentMapper.java
src/test/java/gov/ca/cwds/cans/domain/mapper/AssessmentMapperTest.java

https://osi-cwds.atlassian.net/browse/CANS-757
Add service_source_ui_id to the search assessments endpoint response

CANS-757. Update Case/Referral Number label and Assessment History

---

src/main/java/gov/ca/cwds/cans/CansApplication.java
src/main/java/gov/ca/cwds/cans/security/AssessmentCreateAuthorizer.java
src/main/java/gov/ca/cwds/cans/security/AssessmentReadAuthorizer.java
src/main/java/gov/ca/cwds/cans/security/AssessmentWriteAuthorizer.java
src/main/java/gov/ca/cwds/cans/security/ClientCheckHelper.java
src/test/java/gov/ca/cwds/cans/domain/mapper/AssessmentMapperTest.java
src/test/java/gov/ca/cwds/cans/rest/resource/AssessmentResourceAuthorizationTest.java

https://osi-cwds.atlassian.net/browse/CANS-785
AssessmentCreateAuthorizer was created

CANS-785 Disable New CANS button if user don't have permissions to create assessment

---

src/main/java/gov/ca/cwds/cans/domain/mapper/ClientMapper.java

CANS-682: client county determination bug fix

---

config/cans-api.yml

DB2 connection pulls extended to 20 connections to support a higher concurrent load. Isolation level for DB2 connections switched to Read Uncommitted according to DB2 DBAs recommendation.

Performance improvements. DB2 connection pulls extended to 20 connections. Isolation level for DB2 connections switched to Read Uncommitted.

---

config/cans-api.yml
src/test/resources/config/cans-api.yml

Log pattern fixed to have unique identifiers for each request

Log pattern fixed to have unique identifiers for each request

---

src/test/java/gov/ca/cwds/cans/rest/resource/AssessmentResourceTest.java
src/test/java/gov/ca/cwds/cans/rest/resource/StaffResourceTest.java

Assessment cleanup in tests

---

src/main/java/gov/ca/cwds/cans/security/BaseClientAssessmentAuthorizer.java
src/test/java/gov/ca/cwds/cans/rest/resource/AbstractFunctionalTest.java
src/test/java/gov/ca/cwds/cans/rest/resource/ClientsResourceTest.java
src/test/resources/fixtures/perry-account/0Ht-napa-all-no-sensitive.json

CANS-854: client authorizer bug fix

---

jenkinsfile-pull-request.groovy

DO NOT REVIEW OR MERGE - testing out stuff for FIT-292

WIP - DO NOT REVIEW OR MERGE - FIT 292

---

build.gradle

Update project major version

---

src/main/java/gov/ca/cwds/cans/domain/entity/Person.java
src/test/java/gov/ca/cwds/cans/rest/resource/StaffResourceTest.java

https://osi-cwds.atlassian.net/browse/CANS-877

CANS-877. CANS Reminder Date Refactored

---

src/test/java/gov/ca/cwds/cans/rest/resource/AssessmentResourceTest.java

Functional tests for assessment deletion operation used to run successfully only once in the live environment. Removed broken test and added more test cases.

Fix functional tests for assessment deletion operation
